create database sandwich;
use sandwich;
drop table sandwich;
create table sandwich(caseID VARCHAR(30), ingredient1 VARCHAR(30), ingredient2 VARCHAR(30), ingredient3 VARCHAR(30), ingredient4 VARCHAR(30), ingredient5 VARCHAR(30));
insert into sandwich values("Sandwich1","Bread","Tuna","Oil","Avocado","Lettuce");
insert into sandwich values("Sandwich2","Baguette","Egg","Avocado","Turkey","Mayonnaise");
insert into sandwich values("Sandwich3","Bread","Avocado","Oil","Egg","Turkey");
insert into sandwich values("Sandwich4","Wholemeal","Cheese","Pig","Lettuce","Oil");
insert into sandwich values("Sandwich5","Ciabatta","Chile","Oil","Veal","Cheese");
insert into sandwich values("Sandwich6","Bread","Tuna","Lettuce","Avocado","Margarine");
insert into sandwich values("Sandwich7","Bread","Oil","Avocado","Mayonnaise","Lettuce");
insert into sandwich values("Sandwich8","Bread","Lettuce","Avocado","Oil","Mayonnaise");
insert into sandwich values("Sandwich9","Bread","Lettuce","Lettuce","Oil","Tomato");
insert into sandwich values("Sandwich10","Tuna","Bread","Lettuce","Avocado","Mayonnaise");
insert into sandwich values("Sandwich11","Margarine","Bread","Lettuce","Avocado","Spinach");
insert into sandwich values("Sandwich12","Chile","Veal","Ciabatta","Avocado","Spinach");
insert into sandwich values("Sandwich13","Bread","Tuna","Oil","Avocado","Lettuce");
insert into sandwich values("Sandwich14","Baguette","Egg","Avocado","Turkey","Turkey");
insert into sandwich values("Sandwich15","Bread","Avocado","Oil","Egg","Turkey");
insert into sandwich values("Sandwich16","Wholemeal","Cheese","Pig","Lettuce","Oil");
insert into sandwich values("Sandwich17","Ciabatta","Salmon","Oil","Veal","Cheese");
insert into sandwich values("Sandwich18","Bread","Chicken","Lettuce","Avocado","Mayonnaise");
insert into sandwich values("Sandwich19","Ciabatta","Tomato","Avocado","Ketchup","Lettuce");
insert into sandwich values("Sandwich20","Bread","Lettuce","Margarine","Oil","Salmon");
insert into sandwich values("Sandwich21","Wholemeal","Lettuce","Lettuce","Oil","Mayonnaise");
insert into sandwich values("Sandwich22","Tuna","Bread","Lettuce","Avocado","Chicken");
insert into sandwich values("Sandwich23","Pig","Wholemeal","Lettuce","Avocado","Spinach");
insert into sandwich values("Sandwich24","Chile","Veal","Ciabatta","Avocado","Spinach");
insert into sandwich values("Sandwich25","Bread","Tuna","Oil","Avocado","Lettuce");
insert into sandwich values("Sandwich26","Baguette","Egg","Avocado","Turkey","Mayonnaise");
insert into sandwich values("Sandwich27","Bread","Avocado","Oil","Egg","Spinach");
insert into sandwich values("Sandwich28","Wholemeal","Cheese","Pig","Lettuce","Oil");
insert into sandwich values("Sandwich29","Ciabatta","Chile","Oil","Veal","Cheese");
insert into sandwich values("Sandwich30","Bread","Salmon","Lettuce","Avocado","Chicken");
insert into sandwich values("Sandwich31","Baguette","Oil","Avocado","Ketchup","Lettuce");
insert into sandwich values("Sandwich32","Bread","Tomato","Avocado","Spinach","Spinach");
insert into sandwich values("Sandwich33","Baguette","Lettuce","Lettuce","Oil","Ketchup");
insert into sandwich values("Sandwich34","Tomato","Baguette","Lettuce","Avocado","Tomato");
insert into sandwich values("Sandwich35","Chile","Bread","Lettuce","Salmon","Spinach");
insert into sandwich values("Sandwich36","Margarine","Veal","Ciabatta","Avocado","Spinach");
insert into sandwich values("Sandwich37","Banana","Baguette","Lettuce","Avocado","Tomato");
insert into sandwich values("Sandwich38","Chile","Bread","Lettuce","Tomato","Spinach");
insert into sandwich values("Sandwich39","Pepper","Banana","Ciabatta","Avocado","Spinach");
insert into sandwich values("Sandwich40","Strawberry","Spinach","Ciabatta","Avocado","Spinach");